### ISSUE TITLE
Runelite OSRS doesn't launch 

### ISSUE THREAD

**Issue by coreybruce** [TormStorm/jagex-launcher-linux#119]
**Describe the bug**

**To Reproduce**
1. Go to OSRS
2. select runelite
3. press play

**Expected behavior**
Runelite runs

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/8393780/d1eac5ff-ba9f-4577-a1ba-cb9e568e12ea)

Seems to be having issues with Java17 I assume based on the log

```
Started initial process 138303 from /home/corey/.local/share/lutris/runners/wine/wine-ge-8-22-x86_64/bin/wine /home/corey/Stuff/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/JagexLauncher.exe
Start monitoring process.
fsync: warning: a previous shm file /wine-1449201-fsync was not properly removed
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[2023-11-17 11:28:38.374] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.397] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.421] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.440] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.463] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.487] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.517] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.540] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.563] [MANGOHUD] [info] [blacklist.cpp:68] process 'explorer.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.710] [MANGOHUD] [info] [blacklist.cpp:68] process 'tabtip.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.734] [MANGOHUD] [info] [blacklist.cpp:68] process 'tabtip.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.757] [MANGOHUD] [info] [blacklist.cpp:68] process 'tabtip.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.795] [MANGOHUD] [info] [blacklist.cpp:68] process 'tabtip.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.819] [MANGOHUD] [info] [blacklist.cpp:68] process 'tabtip.exe' is blacklisted in MangoHud
[2023-11-17 11:28:38.842] [MANGOHUD] [info] [blacklist.cpp:68] process 'tabtip.exe' is blacklisted in MangoHud
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-17-openjdk/lib/libnio.so: /usr/lib/jvm/java-17-openjdk/lib/libnio.so: undefined symbol: reuseport_available
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:270)
	at java.base/jdk.internal.loader.BootLoader.loadLibrary(BootLoader.java:149)
	at java.base/sun.nio.fs.UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:667)
	at java.base/sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:65)
	at java.base/sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:46)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:39)
	at java.base/sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:55)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:41)
	at java.base/sun.nio.fs.DefaultFileSystemProvider.<clinit>(DefaultFileSystemProvider.java:35)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:114)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:103)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:101)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:101)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:94)
	at java.base/java.nio.file.FileSystems.getDefault(FileSystems.java:183)
	at java.base/java.io.File.toPath(File.java:2387)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1428)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:256)
	at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:555)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:781)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:689)
```
Standalone Runelite works just fine but since I upgraded my account not knowing I can no longer use it I am forced to use the Jagex-launcher

Here is standalone Runelte working with java-17

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/8393780/c3667a54-8d0e-4f08-abe4-9fd07d01490f)

**Hardware information**
```
[System]
OS:              Manjaro Linux 23.1.0 Vulcan
Arch:            x86_64
Kernel:          6.1.62-1-MANJARO
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.4 GB
Swap:            8.8 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.9-manjaro1.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.9-manjaro1.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.9-manjaro1.1
Vulkan Version:  1.3.269
Vulkan Drivers:  NVIDIA GeForce GTX 1660 Ti (1.3.242)
```

**Comment by nmlynch94** [comment]
Yeah may be incompatibilities with your jdk provider. Try out enabling prefer system libraries https://github.com/TormStorm/jagex-launcher-linux/wiki/Troubleshooting#not-using-flatpak.

**Comment by coreybruce** [comment]
Oh I see well I am using the lutris package in my repo and not the flatpak so how do I select my preferred java version in normal lutris?

**Comment by nmlynch94** [comment]
Try unchecking "Prefer System Libraries" from that screenshot.

**Comment by coreybruce** [comment]
Yep that works!

Now to figure out why my game is running at 7fps, I assume it has to do with the game using my igpu instead of the dedicated gpu

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/8393780/87874955-ecc5-4971-b0cf-a75d7fc2a2b9)

**Comment by nmlynch94** [comment]
Try editing runelite.sh in Lutris -> Right Click -> Browse Files -> drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/runelite.sh

And edit it to be `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia java -jar "$(pwd)"/Games/RuneLite/RuneLite.jar`

**Comment by coreybruce** [comment]
> Try editing runelite.sh in Lutris -> Right Click -> Browse Files -> drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/runelite.sh
> 
> And edit it to be `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia java -jar "$(pwd)"/Games/RuneLite/RuneLite.jar`

Yeah that worked!

**Comment by coreybruce** [comment]
I'll close the issue post
